site_name: Gator
repo_name: intuity/gator
repo_url: https://github.com/intuity/Gator
theme:
  name: material
  logo: assets/mascot_black.svg
  palette:
    scheme: slate
    primary: amber
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Welcome: "index.md"
  - "How Gator Works": "how_it_works.md"
  - Schedulers: "schedulers.md"
  - "YAML Specification":
    - "!Job": "specs/job.md"
    - "!JobArray": "specs/job_array.md"
    - "!JobGroup": "specs/job_group.md"
    - "!Cores": "specs/cores.md"
    - "!License": "specs/license.md"
    - "!Memory": "specs/memory.md"
  - "Websocket API": "websocket_api.md"
