site_name: Gator
theme:
  name: material
  logo: assets/mascot_black.svg
  palette:
    scheme: slate
    primary: amber
markdown_extensions:
  - attr_list
nav:
  - Welcome: "index.md"
  - "YAML Specification":
    - "!Job": "specs/job.md"
    - "!JobArray": "specs/job_array.md"
    - "!JobGroup": "specs/job_group.md"
