[tool.poetry]
name = "gator"
version = "1.0"
description = "Hierarchical job execution and logging"
authors = ["Peter Birch <peter@lightlogic.co.uk>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
plotly = "^5.14.1"
psutil = "^5.9.4"
pandas = "^2.0.0"
kaleido = "0.2.1"
requests = "^2.28.2"
flask = "^2.2.3"
rich = "^13.3.4"
tabulate = "^0.9.0"
pyyaml = "^6.0"
uwsgi = "^2.0.21"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.6"
poethepoet = "^0.19.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=gator --cov-branch --cov-report html --cov-report term -x"
testpaths = ["tests"]

[tool.poe.tasks]
uwsgi = "uwsgi --http 127.0.0.1:8080 --master -p 4 -w gator.hub.app:hub"
