!JobGroup
ident: test_group
jobs:
  - !Job
      ident  : job_a
      command: sleep
      args   :
        - 10
  - !JobGroup
      ident: nested
      jobs:
        - !Job
            ident  : job_b
            command: echo
            args   :
              - "This is B"
        - !Job
            ident  : job_c
            command: echo
            args   :
              - "This is C"
