!JobGroup
ident: top
jobs:
- !JobGroup
  ident: path_a
  jobs:
  - !Job
      ident: msg_emitter
      command: python3
      args:
        - emitter.py
        - 10000
        - A
      resources:
        - !Cores [1]
        - !Memory [30, MB]
- !JobGroup
  ident: path_b
  jobs:
  - !Job
      ident: msg_emitter
      command: python3
      args:
        - emitter.py
        - 10000
        - B
      resources:
        - !Cores [1]
        - !Memory [30, MB]
