name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry poethepoet
    - name: Setup environment
      run: |
        poetry install --with dev
    - name: Run lint
      run: |
        poe lint
    - name: Run tests
      timeout-minutes: 5
      run: |
        poe test
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-cov
        path: htmlcov
    - name: Build documentation
      run: |
        poetry run mkdocs build
    - name: Archive documentation
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: site
